// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDatabase(arg1, arg2) {
  return window['go']['main']['App']['AddDatabase'](arg1, arg2);
}

export function GetDatabases() {
  return window['go']['main']['App']['GetDatabases']();
}

export function GetDatabasesList(arg1) {
  return window['go']['main']['App']['GetDatabasesList'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
