// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDatabase(arg1:string,arg2:string):Promise<void>;

export function GetDatabases():Promise<Array<main.DatabaseConnection>>;

export function GetDatabasesList(arg1:string):Promise<{[key: string]: Array<main.TableInfo>}>;

export function TestConnection(arg1:string):Promise<void>;
